name: Fuzzing

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  fuzz:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Clang
      run: |
        sudo apt-get update
        sudo apt-get install -y clang llvm

    - name: Configure CMake for Fuzzing
      run: |
        cmake -S . -B build_fuzz -DENABLE_FUZZING=ON -DCMAKE_BUILD_TYPE=Debug
      env:
        CC: clang
        CXX: clang++

    - name: Build all fuzz targets
      run: cmake --build build_fuzz --config Debug # This will build all executables configured for the Debug build

    - name: Create corpus directories
      run: |
        mkdir -p build_fuzz/corpus_fuzzing/fuzz_bitmap_corpus
        mkdir -p build_fuzz/corpus_fuzzing/fuzz_bmp_tool_save_corpus
        mkdir -p build_fuzz/corpus_fuzzing/fuzz_bitmap_file_corpus
        mkdir -p build_fuzz/corpus_fuzzing/fuzz_image_operations_corpus
        mkdir -p build_fuzz/corpus_fuzzing/fuzz_matrix_corpus
        mkdir -p build_fuzz/corpus_fuzzing/fuzz_convert_bgr_to_bgra_corpus
        mkdir -p build_fuzz/corpus_fuzzing/fuzz_swizzle_bgra_to_rgba_corpus
        mkdir -p build_fuzz/corpus_fuzzing/fuzz_swizzle_rgba_to_bgra_corpus

    - name: Run fuzz_bitmap
      run: |
        ./build_fuzz/tests/fuzz_bitmap -max_total_time=60 -print_final_stats=1 -print_pcs=1 -error_exitcode=1 build_fuzz/corpus_fuzzing/fuzz_bitmap_corpus/
    
    - name: Run fuzz_bmp_tool_save
      run: |
        ./build_fuzz/tests/fuzz_bmp_tool_save -max_total_time=60 -print_final_stats=1 -print_pcs=1 -error_exitcode=1 build_fuzz/corpus_fuzzing/fuzz_bmp_tool_save_corpus/

    - name: Run fuzz_bitmap_file
      run: |
        ./build_fuzz/tests/fuzz_bitmap_file -max_total_time=60 -print_final_stats=1 -print_pcs=1 -error_exitcode=1 build_fuzz/corpus_fuzzing/fuzz_bitmap_file_corpus/

    - name: Run fuzz_image_operations
      run: |
        ./build_fuzz/tests/fuzz_image_operations -max_total_time=60 -print_final_stats=1 -print_pcs=1 -error_exitcode=1 build_fuzz/corpus_fuzzing/fuzz_image_operations_corpus/

    - name: Run fuzz_matrix
      run: |
        ./build_fuzz/tests/fuzz_matrix -max_total_time=60 -print_final_stats=1 -print_pcs=1 -error_exitcode=1 build_fuzz/corpus_fuzzing/fuzz_matrix_corpus/
    
    - name: Run fuzz_convert_bgr_to_bgra
      run: |
        ./build_fuzz/tests/fuzz_convert_bgr_to_bgra -max_total_time=60 -print_final_stats=1 -print_pcs=1 -error_exitcode=1 build_fuzz/corpus_fuzzing/fuzz_convert_bgr_to_bgra_corpus/
    
    - name: Run fuzz_swizzle_bgra_to_rgba
      run: |
        ./build_fuzz/tests/fuzz_swizzle_bgra_to_rgba -max_total_time=60 -print_final_stats=1 -print_pcs=1 -error_exitcode=1 build_fuzz/corpus_fuzzing/fuzz_swizzle_bgra_to_rgba_corpus/

    - name: Run fuzz_swizzle_rgba_to_bgra
      run: |
        ./build_fuzz/tests/fuzz_swizzle_rgba_to_bgra -max_total_time=60 -print_final_stats=1 -print_pcs=1 -error_exitcode=1 build_fuzz/corpus_fuzzing/fuzz_swizzle_rgba_to_bgra_corpus/
